name: Deploy HeyEmoji (Testing)

on:
  workflow_dispatch:
    inputs:
      stack_destroy:  
        type: boolean
        default: false
      create_efs:  
        type: boolean
        default: false
      efs_zone_mapping:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@nfs
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        stack_destroy: ${{ github.event.inputs.stack_destroy }}
        create_efs: ${{ github.event.inputs.create_efs }}
        efs_zone_mapping: ${{ github.event.inputs.efs_zone_mapping }}
