name: Deploy Community HeyEmoji

on:
  workflow_dispatch:
    inputs:
      aws-default-region:
        type: string
        description: AWS Region targeted for deployment
        default: us-east-
      destroy:
        type: choice
        options:
          - true
          - false
        default: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.1.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: ${{ github.event.inputs.aws-default-region }}
        dot_env: ${{ secrets.DOT_ENV_COMMUNITY }}
        app_port: 3334
        tf_state_bucket: bitovi-community-heyemoji-main-tf-state
        stack_destroy: ${{ github.event.inputs.destroy }}
