name: Deploy HeyEmoji (Testing)

on:
  workflow_dispatch:
    inputs:
      stack_destroy:  
        type: boolean
        default: false
      # create_efs:  
      #   type: boolean
      # create_ha_efs:
      #   type: boolean
      # create_efs_replica:
      #   type: boolean
      # enable_efs_backup_policy:
      #   type: boolean
      # efs_zone_mapping:
      #   type: string
      # efs_transition_to_inactive:
      #   type: string
      # replication_configuration_destination:
      #   type: string
      # aws_default_region:
      #   type: string
      mount_efs_id:
        type: string
      mount_efs_security_group_id:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      name: Deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@nfs
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        # aws_default_region: ${{ github.event.inputs.aws_default_region }}
        stack_destroy: ${{ github.event.inputs.stack_destroy }}
        create_efs: ${{ github.event.inputs.create_efs }}
        create_ha_efs: ${{ github.event.inputs.create_ha_efs }}
        create_efs_replica: ${{ github.event.inputs.create_efs_replica }}
        enable_efs_backup_policy: ${{ github.event.inputs.enable_efs_backup_policy }}
        efs_zone_mapping: ${{ github.event.inputs.efs_zone_mapping }}
        efs_transition_to_inactive: ${{ github.event.inputs.efs_transition_to_inactive }}
        replication_configuration_destination: ${{ github.event.inputs.replication_configuration_destination }}
        mount_efs_id: ${{ github.event.inputs.mount_efs_id }}
        mount_efs_security_group_id: ${{ github.event.inputs.mount_efs_security_group_id }}
        targets: ${{ github.event.inputs.targets }}
