name: Deploy or Destroy HeyEmoji (AWS:EC2)

on:
  workflow_dispatch:
    inputs:
      destroy:
        type: choice
        options:
          - false
          - true
      mount_efs_id:
        type: string

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@fix_efs_mount
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_HEYEMOJI }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_HEYEMOJI }}
        dot_env: ${{ secrets.DOT_ENV_INTERNAL }}
        ghv_env: ${{ vars.DOT_ENV_INTERNAL }}
        app_port: 3334
        stack_destroy: ${{ github.event.inputs.destroy }}
        aws_mount_efs_id: ${{ github.event.inputs.mount_efs_id }}
